list_all_users:
    path:     /users/all
    defaults: { _controller: UserBundle:Default:listAllUsers }

send_message:
    path:     /send-message/{username}
    defaults: { _controller: UserBundle:Default:sendMessage }
