services:
    twig.extension.notification_nb:
        class: NajahHost\UserBundle\Twig\NotificationExtension
        arguments:
              doctrine: "@doctrine"
              user: "@security.context"
        tags:
            - { name: twig.extension }
